### ISSUE TITLE
validate_date

### ISSUE THREAD

**Issue by murtyk** [Vydia/gourami#2]
how about adding validate_date? It should validate the string "YYYYMMDD" as a valid date.

**Comment by TSMMark** [comment]
I'm not sure we can be so opinionated about how a date string should be formatted. However, if you wanted to validate the pattern "YYYYMMDD" where each character is a digit, you could use [`validate_format`](https://github.com/Vydia/gourami/blob/abdba1c08187f49ac53398a40440f6617c326fca/lib/gourami/validations.rb#L126).

```ruby
validate_format(:my_date_attribute, /^\d{6}$/)
```
